services:
  - type: web
    name: exercise-form-corrector
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: models
      mountPath: /opt/render/project/src
      sizeGB: 1